-- Nautilus: dados de exemplo para teste read-only (Oracle)
CREATE TABLE departments (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE employees (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(200) NOT NULL,
  department_id NUMBER,
  salary NUMBER(12,2),
  hired_at DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_emp_dept FOREIGN KEY (department_id) REFERENCES departments(id)
);

CREATE TABLE products (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(200) NOT NULL,
  price NUMBER(12,2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO departments (id, name) VALUES (1, 'Vendas');
INSERT INTO departments (id, name) VALUES (2, 'TI');
INSERT INTO departments (id, name) VALUES (3, 'RH');

INSERT INTO employees (id, name, department_id, salary, hired_at) VALUES (1, 'Ana Silva', 1, 5500.00, DATE '2022-03-15');
INSERT INTO employees (id, name, department_id, salary, hired_at) VALUES (2, 'Bruno Santos', 2, 7200.00, DATE '2021-06-01');
INSERT INTO employees (id, name, department_id, salary, hired_at) VALUES (3, 'Carla Oliveira', 1, 4800.00, DATE '2023-01-10');
INSERT INTO employees (id, name, department_id, salary, hired_at) VALUES (4, 'Diego Costa', 2, 6800.00, DATE '2020-11-20');
INSERT INTO employees (id, name, department_id, salary, hired_at) VALUES (5, 'Elena Ferreira', 3, 5100.00, DATE '2022-08-05');

INSERT INTO products (id, name, price) VALUES (1, 'Notebook Pro', 4500.00);
INSERT INTO products (id, name, price) VALUES (2, 'Mouse Wireless', 120.00);
INSERT INTO products (id, name, price) VALUES (3, 'Teclado Mecânico', 380.00);
INSERT INTO products (id, name, price) VALUES (4, 'Monitor 27"', 1200.00);
INSERT INTO products (id, name, price) VALUES (5, 'Webcam HD', 250.00);

COMMIT;
